# Azure DevOps pipeline to release a new version and deploy to production.

variables:
  HEALTHCHECK_PATH: 'api/v1/info' 

parameters:
  - name: 'RELEASE_SEMVER'
    displayName: 'When packing a release, define the version bump to apply'
    type: string
    values:
      - major
      - minor
      - patch
    default: minor

# Only manual activations are intended
trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

resources:
  repositories:
    - repository: pagopaCommons
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v19
      endpoint: 'io-azure-devops-github-ro'

stages:

  # Create a relase
  # Activated when ONE OF these are met:
  # - is on branch main 
  # - is a tag in the form v{version}-RELEASE
  - stage: Release
    condition:
      and(
        succeeded(),
        or(
          eq(variables['Build.SourceBranch'], 'refs/heads/main'),
          and(
            startsWith(variables['Build.SourceBranch'], 'refs/tags'),
            endsWith(variables['Build.SourceBranch'], '-RELEASE')
          )
        )
      )
    jobs:
      - job: make_release
        steps:
        - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
          - template: templates/node-job-setup/template.yaml@pagopaCommons
            parameters:
              persistCredentials: true
          - template: templates/node-github-release/template.yaml@pagopaCommons
            parameters:
              semver: '${{ parameters.RELEASE_SEMVER }}'
              gitEmail: $(GIT_EMAIL)
              gitUsername: $(GIT_USERNAME)
              gitHubConnection: $(GITHUB_CONNECTION)
              release_branch: main

        - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/main') }}:
          - script: |
              echo "We assume this reference to be a valid release: $(Build.SourceBranch). Therefore, there is no need to bundle a new release."
            displayName: 'Skip release bundle'
  
  - stage: Apply_Database_Schema
    dependsOn: 
      - Release
    pool:
      name: io-prod-linux
    jobs:
      - job: make_migration
        steps:
          - task: AzureCLI@2
            displayName: migrate db schema
            inputs:
              azureSubscription: '$(PRODUCTION_AZURE_SUBSCRIPTION)'
              scriptType: "bash"
              scriptLocation: "inlineScript"
              failOnStandardError: false
              inlineScript: |
                set -e
                
                # THIS IS THE PRODUCTION SCHEMA NAME, SO PLEASE DON'T CHANGE IT
                SCHEMA_NAME=SelfcareIOSubscriptionMigrations

                ./scripts/run_flyway_on_azure.sh migrate db PROD-IO schema/migrations "${SCHEMA_NAME}" \
                  && echo "Migration successful" \
                  || { echo "Migration failed"; exit 1; }

  # Prepare Artifact
  - stage: Deploy_staging
    dependsOn:
      - Release
    jobs:
      - job: 'prepare_artifact_and_deploy'
        steps:
          # Build application
          - template: templates/node-job-setup/template.yaml@pagopaCommons
            parameters:
              # On the assumption that this stage is executed only when Relase stage is,
              #  with this parameter we set the reference the deploy script must pull changes from.
              # The branch/tag name is calculated from the source branch
              #  ex: Build.SourceBranch=refs/heads/main --> main
              #  ex: Build.SourceBranch=refs/tags/v1.2.3-RELEASE --> v1.2.3-RELEASE
              gitReference: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/tags/', ''), 'refs/heads/', '') }}
          - script: |
              yarn predeploy
            displayName: 'Build'

          # Install functions extensions
          - task: DotNetCoreCLI@2
            inputs:
              command: "build"
              arguments: "-o bin"   
          # Copy application to  
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              Contents: |
                **/*
                !.git/**/*
                !**/*.js.map
                !**/*.ts
                !.vscode/**/*
                !azure-templates/**/*
                !azure-pipelines.yml
                !.prettierrc
                !.gitignore
                !README.md
                !jest.config.js
                !local.settings.json
                !test
                !tsconfig.json
            displayName: 'Copy deploy files'
            
          - task: AzureFunctionApp@1  
            inputs:
              azureSubscription: '$(PRODUCTION_AZURE_SUBSCRIPTION)'
              resourceGroupName: '$(PRODUCTION_RESOURCE_GROUP_NAME)'
              appType: 'functionApp'
              appName: '$(PRODUCTION_APP_NAME)'
              package: '$(Build.ArtifactStagingDirectory)/'
              deploymentMethod: 'auto'
              deployToSlotOrASE: true
              slotName: 'staging'
            displayName: Deploy to staging slot

  # Check that the staging instance is healthy
  - stage: Healthcheck
    pool:
      name: io-prod-linux
    dependsOn:
      - Deploy_staging
    jobs:
      - job: 'do_healthcheck'       
        steps:  
        - checkout: none
        - script: |
            hc_url="https://$(PRODUCTION_APP_NAME)-staging.azurewebsites.net/$(HEALTHCHECK_PATH)"
            echo "Healthcheck url: $hc_url"
            # fails if response status is not 2xx
            curl -f "$hc_url"
          displayName: 'Healthcheck'

  # Promote the staging instance to production
  - stage: Deploy_production
    dependsOn:
      - Healthcheck
      - Deploy_staging
    jobs:
      - job: 'do_deploy'       
        steps:  
          - task: AzureAppServiceManage@0   
            inputs:
              azureSubscription: '$(PRODUCTION_AZURE_SUBSCRIPTION)'
              resourceGroupName: '$(PRODUCTION_RESOURCE_GROUP_NAME)'
              webAppName: '$(PRODUCTION_APP_NAME)'
              sourceSlot: staging
              swapWithProduction: true
            displayName: Swap with production slot


  # Publish client SDK to NPM
  - stage: PublishClientSDKtoNPM
    dependsOn: Release
    jobs:
      - job: publish_SDK   
        steps:
        # Template for generating and deploying client SDk to NPM
        - template: templates/client-sdk-publish/template.yaml@pagopaCommons
          parameters:
            openapiSpecPath: 'openapi/index.yaml'
