name: Publish SDK - PROD

on:
  workflow_dispatch:
  push:
    branches:
      - EC-398-devops-decommissioning

jobs:
  deploy_on_prod:
    uses: ./.github/workflows/publish-sdk.yaml
    name: Publish SDK on PROD
    secrets: inherit
    with:
      environment: 'prod'
      use_private_agent: false
      openapiSpecPath: openapi/index.yaml
